"""add embedding columns to resumes

Revision ID: a67db63b491d
Revises: 4be2a2208cb6
Create Date: 2026-05-19 18:43:51.299785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a67db63b491d'
down_revision: Union[str, Sequence[str], None] = '4be2a2208cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('resume_embedding', sa.JSON(), nullable=True))
    op.add_column('resumes', sa.Column('jd_embedding', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'jd_embedding')
    op.drop_column('resumes', 'resume_embedding')
    # ### end Alembic commands ###
